name: movie_list
description: Browse popular movies

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_mobx: ^2.0.6+3
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  mobx: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  freezed: ^2.0.5
  json_serializable: ^6.4.1
  mobx_codegen: ^2.0.7+3
  mockito: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/next.png
